repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.701'
    hooks:
    -   id: mypy
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.12.4
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.0'
    hooks:
    - id: bandit
      args: ['--exclude', 'tests,.venv']
