language: python
python: "3.6"
dist: xenial

stages:
  - lint
  - test
  - deploy

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pip install poetry
        - poetry install -v
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - pytest --cov=pyartifactory --cov-branch --cov-report=xml
        - python-codacy-coverage -r coverage.xml
    - stage: deploy
      script:
        - pip install --upgrade pip
        - pip install poetry
        - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          repo: anancarv/python-artifactory     # Deploy only when the build occurs on a particular repository
          tags: true
