[tool.poetry]
name = "PyArtifactory"
version = "0.1.0"
description = ""
authors = ["Ananias CARVALHO <ananias.carvalho@ext.adeo.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pydantic = "^0.23.0"
requests = "^2.21"
email_validator = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "^0.700.0"
black = { version = "^19.3b0", allows-prereleases = true }
pre-commit = "^1.15"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
