[tool.poetry]
name = "python-artifactory"
version = "0.1.0"
description = ""
authors = ["Ananias CARVALHO <carvalhoananias@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pydantic = "^0.23.0"
requests = "^2.21"
email_validator = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "^0.700.0"
black = { version = "^19.3b0", allows-prereleases = true }
pre-commit = "^1.15"
responses = "^0.10.6"
pytest-mock = "^1.10"
bandit = "^1.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
